# .github/workflows/release.yaml

on:
  push:
    branches: [ "action-workflow" ]
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: "action-workflow"

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'  # Set your required Go version here

      - name: Build binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o output/widdler-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: widdler-${{ matrix.goos }}-${{ matrix.goarch }}
          path: output/widdler-${{ matrix.goos }}-${{ matrix.goarch }}
